### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by PancakeTAS** [MinecraftTAS/TAS-Battle#12]
The tasbattle client should be kept very similar to the [old one](https://github.com/MinecraftTAS/TAS-Battle/tree/old/TAS-Client)

These features can be taken from the old client and reimplemented *better*:
- tickrate changer
- replay mod support (variable tickrate support)
- custom capes
- custom tags
- auto updating

These features have some changes:
- tas maps will be reimplemented entirely - for now a custom world selection screen where a map can be selected with icon name and longer description will suffice. (i believe similar to the realms screen)
- player spectating should work similar just less painful. there should be a way to toggle between spectating in first person and third person, where the third person camera can also switch between being inside of blocks or automatically being near the player.
- joining the server will just be a single button in the main menu now

New features:
- discord rich presence (possibly with player inviting should become a thing)
- secret dev mode when idk shift clicking the join button should go to preview.mgnet.work instead of mgnet.work

@ScribbleTAS For this first pull request - tickrate changer, joining the server (including the secret mode) and the new spectating system.

**Comment by ScribbleTAS** [comment]
@PancakeTAS I see what mood you had when you were trying to fix this code
```java
int FUCKYOUJAVAIWILLKILLYOU = i;
```
1. I assume the anarchy server isn't needed anymore...
2. As you reprogram a lot of stuff anyway, how about we release the standalone server software so people stop asking for it? Maybe this will broaden the TAS-Battle community as a whole and brings in more people, as supposed to gating the growth by not allowing custom servers... Thats why maybe a "Private Server" option should be added to the menu, next to an "Official Server" instead of the singleplayer button.
3. I don't see any anticheat here, should that be reimplemented?

**Comment by ScribbleTAS** [comment]
Also even better is the question: What version should the client have? Was it 1.19.3?

**Comment by PancakeTAS** [comment]
> @PancakeTAS I see what mood you had when you were trying to fix this code
> 
> ```java
> int FUCKYOUJAVAIWILLKILLYOU = i;
> ```
> 
> 1. I assume the anarchy server isn't needed anymore...
> 2. As you reprogram a lot of stuff anyway, how about we release the standalone server software so people stop asking for it? Maybe this will broaden the TAS-Battle community as a whole and brings in more people, as supposed to gating the growth by not allowing custom servers... Thats why maybe a "Private Server" option should be added to the menu, next to an "Official Server" instead of the singleplayer button.
> 3. I don't see any anticheat here, should that be reimplemented?

Anarchy server is not needed anymore. 
No I will not release tas battle for private servers, they can use lotas for that.
Anti cheat is server side and already implemented (see Gameserver/src/common/)

Client is 1.19.4 without fabric api
