### ISSUE TITLE
Spectating System

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TAS-Battle#13]
I had a bit of thought about a better spectating system for FFA and maybe this is something worth thinking about.

# The problem
Having the spectator orbit around one player in third person may miss some of the action between the pvpers.

# The solution
![MicrosoftWhiteboard_8Slnw1OZOz](https://github.com/MinecraftTAS/TAS-Battle/assets/28013575/30cac806-fcff-43eb-bc02-66285e07d8ec)
Here we have 2 players (blue). We are currently spectating the light blue player. Every player has an area around them (red). If a player enters the area, we set the orbiting point exactly between the 2 players (yellow).

Even better, we can change the zoom factor of the orbit camera depending on the distance between the players.

For 3 players we can set the orbiting point in the middle of the triangle:
![MicrosoftWhiteboard_diFEeov9Ka](https://github.com/MinecraftTAS/TAS-Battle/assets/28013575/fdba796c-1000-484e-87a6-b4e699a2f847)

# Conclusion
Not strictly necessary of course and maybe too complicated, but this might be a fun thing.Might also take a lot of trial and error to get right but might be worth it.

**Comment by PancakeTAS** [comment]
sounds cool might look at implementing it at a later time
