### ISSUE TITLE
Spectating system is very unintuitive

### ISSUE THREAD

**Issue by PancakeTAS** [MinecraftTAS/TAS-Battle#70]
#13 can be made some other time..
This issue has to be fixed before release

**Comment by ScribbleTAS** [comment]
So my thought was to make cycling between players a bit better, bc i hate the vanilla system... plus not interfering with existing vanilla buttons...

My ideal system would be q prev player, e next player, rightclick next spectating mode, leftclick prev... Space to start spectating the nearest player...

As a suggestion only, i know it's not possible

**Comment by PancakeTAS** [comment]
i want to replace the vanilla menu (which is hella bad in tr4) with my own one to cycle through players. it'd achieve the same things just easier
